name: CPP Unit Tests
on: 
  push:
    branches: [main]
    paths:
      - 'cpp/**.cpp'
      - 'cpp/**.h'
      - 'cpp/**.hpp'
      - 'cpp/CMakeLists.txt'
      - '.github/workflows/cpp-unit-test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'cpp/**.cpp'
      - 'cpp/**.h'
      - 'cpp/**.hpp'
      - 'cpp/CMakeLists.txt'
      - '.github/workflows/cpp-unit-test.yml'
  workflow_dispatch:
    
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: CMake Configure
        working-directory: ./cpp
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        working-directory: ./cpp
        run: cmake --build build --target UnitTests --config Release

      - name: Execute tests
        working-directory: ./cpp
        run: ctest --test-dir build --output-on-failure --output-junit cpp-output.xml
      
      - name: Upload JUnit file
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: cpp-result
          path: ./cpp/build/cpp-output.xml
  comment-pr:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{always() && github.event_name == 'pull_request'}}
    needs: unit-test
    steps:
      - name: Github Script
        uses: actions/github-script@v7
        with:
          script: |
            let result;
            if ('${{ needs.unit-test.result }}' === 'success') {
              result = '✅'
            } else if ('${{ needs.unit-test.result }}' === 'failure') {
              result = '❌';
            } else {
              result = '❓';
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${result} ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/run/${context.runId}`
            });
  test-reporter:
    if: always()
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Download Artifact cpp
        uses: actions/download-artifact@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        with:
          name: cpp-report
      
      - name: Test Report
        uses: dorny/test-reporter@v3
        with:
          name: Résultats Unit Tests CPP
          path: '**/results.xml'
          reporter: java-junit
