name: CPP Unit Tests
on: 
  workflow_dispatch:
  push:
    branches: [unit-test-action]
    paths:
      - 'cpp/**.cpp'
      - 'cpp/**.h'
      - 'cpp/**.hpp'
      - 'cpp/CMakeLists.txt'
      - '.github/workflows/cpp-unit-test.yml'
  pull_request:
    branches: [unit-test-action]
    paths:
      - 'cpp/**.cpp'
      - 'cpp/**.h'
      - 'cpp/**.hpp'
      - 'cpp/CMakeLists.txt'
      - '.github/workflows/cpp-unit-test.yml'
    
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: CMake Configure
        working-directory: ./cpp
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        working-directory: ./cpp
        run: cmake --build build --target UnitTests --config Release

      - name: Execute tests
        working-directory: ./cpp
        run: ctest --test-dir build --output-on-failure
