name: Go Unit Tests
on: 
  push:
    branches: [unit-test-action]
    paths:
      - 'go/**.go'
      - 'go/**.mod'
      - 'go/**.sum'
      - '.github/workflows/go-unit-test.yml'
  pull_request:
    branches: [unit-test-action]
    paths:
      - 'go/**.go'
      - 'go/**.mod'
      - 'go/**.sum'
      - '.github/workflows/go-unit-test.yml'
  workflow_dispatch:
    
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with: 
          go-version-file: go/go.mod
      
      - name: Install gotestsum for report
        run: go install gotest.tools/gotestsum@latest

      - name: Build Go
        working-directory: ./go
        run: go build ./...
      
      - name: Test Go
        working-directory: ./go
        run: gotestsum --format testname --junitfile go-output.xml -- ./...
      
      - name: Upload JUnit file
        uses: actions/upload-artifact@v7
        with:
          name: go-result
          path: ./go/go-output.xml