name: Unit Test Report
on: 
  workflow_run:
    workflows: [CPP Unit Tests, Go Unit Tests]
    types:
      - completed
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello